### PR TITLE
Discover all dicom files

### PR DESCRIPTION
**Pull request by v-chakradhar-s**

### CODE REVIEW

**Comment by jfphilbin** [comment]
This pull request seems to be against the Master branch, it should be against 0.1.0-Dev. Can you update it against that branch?

Thanks.

Jim Philbin

Co-Chair, DICOM Standards Committee

Principal

Poplar Hill Informatics

jfphilbin@gmail.com

**Comment by v-chakradhar-s** [comment]
Current pull request is not against 0.1.0-Dev,  So closing the pull request.

**Comment by jfphilbin** [comment]
This pull request is against Master branch, but it should be against 0.1.0-Dev.1 branch.  Please fix.

**Comment by jfphilbin** [comment]
Let me know if you have questions or if I can help.  I'm in meetings at ACR tomorrow morning, but should be able to answer emails.

**Pull request closed without merging**
